In [1]:
import tensorflow as tf

In [4]:
arr1=tf.constant([5.2,2.2,3.2])
arr2=tf.constant([6.2,2.5,3.7])
result=tf.global_variables_initializer()
with tf.Session() as session:
    session.run(result)
    print(session.run(arr1))
with tf.Session() as session:
    session.run(result)
    print(session.run(arr2))

[ 5.19999981  2.20000005  3.20000005]
[ 6.19999981  2.5         3.70000005]


In [5]:
sum=tf.add(arr1,arr2)
with tf.Session() as session:
    session.run(sum)
    print(session.run(sum))

[ 11.39999962   4.69999981   6.9000001 ]


In [17]:
mean_arr1=tf.reduce_mean(arr1)
with tf.Session() as session:
    session.run(mean_arr1)
    print(session.run(mean_arr1))

3.53333


In [24]:
mean_arr2=tf.reduce_mean(arr2)
with tf.Session() as session:
    session.run(mean_arr2)
    print(session.run(mean_arr2))

4.13333


In [31]:
###1.Calculate variance for x : variance(x)=sum((x−mean(x))2)
rhs=tf.subtract(arr1,mean_arr1)
with tf.Session() as session:
    session.run(rhs)
    print(session.run(rhs))
### squaring the values of array!!! 
squaring_rhs=tf.square(rhs)
variance=tf.reduce_mean(squaring_rhs)
with tf.Session() as session:
    session.run(variance) ### phewwwwwww the varinace
    print("hey, here's the variance")
    print(session.run(variance))

[ 1.66666675 -1.33333302 -0.33333302]
hey, here's the variance
1.55556


In [16]:
### squaring the values of array!!! 
squaring_rhs=tf.square(rhs)
variance=tf.reduce_mean(squaring_rhs)
with tf.Session() as session:
    session.run(variance) ### phewwwwwww the varinace
    print("hey, here's the variance")
    print(session.run(variance))

hey, here's the variance
1.55556


In [28]:
###Calculate covariance of x & y 
###covariance=sum((x(i)−mean(x))∗(y(i)−mean(y)))
for_arr1=tf.subtract(arr1,mean_arr1)
with tf.Session() as session:
    session.run(for_arr1)
    print(session.run(for_arr1))
for_arr2=tf.subtract(arr2,mean_arr2)
with tf.Session() as session:
    session.run(for_arr2)
    print(session.run(for_arr2))
mul=tf.multiply(for_arr1,for_arr2)
with tf.Session() as session:
    session.run(mul)
    print(session.run(mul))
cov=tf.reduce_mean(mul)
with tf.Session() as session:
    session.run(cov)
    print(session.run(cov))

[ 1.66666675 -1.33333302 -0.33333302]
[ 2.0666666  -1.63333321 -0.43333316]
[ 3.44444442  2.17777705  0.14444424]
1.92222


In [29]:
###value of m
val_m=tf.divide(cov,variance)
with tf.Session() as session:
    session.run(val_m)
    print(session.run(val_m))

1.23571


In [33]:
###Calculate value of c : c=mean(y)−m∗mean(x)
sub_step=tf.multiply(val_m,mean_arr1)
with tf.Session() as session:
    session.run(sub_step)
    print(session.run(sub_step))
val_c=tf.subtract(mean_arr2,sub_step)
with tf.Session() as session:
    session.run(val_c)
    print("you know what??????, it's over!!!= Thus the 'C'")
    print(session.run(val_c))

4.36619
you know what??????, it's over!!!= Thus the 'C'
-0.232857
